/* eslint-disable @typescript-eslint/no-explicit-any */
export const generateReport = (data: any) => {
  const rawUrl = data.repo_url || "Benchmark_Result";
  const metrics = data.metrics || { total_time_ms: 0, peak_memory_kb: 0 };
  const analysis = data.analysis || { score: "N/A", suggestions: ["No data"] };
  const profile = data.profile || [];

  const repoName = rawUrl.split("/").pop() || "Result";
  const formatFile = (path: string) =>
    path.includes("/") ? path.split("/").pop() : path;

  const filteredProfile = profile
    .filter(
      (f: any) =>
        !f.n.includes("<") &&
        !f.f.includes("~") &&
        !f.f.includes("frozen"),
    )
    .sort((a: any, b: any) => b.t - a.t)
    .slice(0, 5);

  const reportContent = `
# MetricCull Performance Report: ${repoName}
Generated on: ${new Date().toLocaleString()}

## Core Metrics
- **Execution Time:** ${metrics.total_time_ms}ms
- **Peak Memory:** ${(metrics.peak_memory_kb / 1024).toFixed(2)} MB
- **AI Efficiency Score:** ${analysis.score}

## AI Logic Analysis
${analysis.suggestions.map((s: string) => `* ${s}`).join("\n")}

## Hot Paths (Top Bottlenecks)
| Function | File:Line | Time (s) |
|----------|-----------|----------|
${
  filteredProfile.length > 0
    ? filteredProfile
        .map(
          (f: any) =>
            `| ${f.n} | ${formatFile(f.f)}:${f.l} | ${f.t.toFixed(4)}s |`,
        )
        .join("\n")
    : "| No significant bottlenecks detected | - | - |"
}

---
*Report generated by MetricCull Advanced Profiling Engine*
  `;

  const blob = new Blob([reportContent], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `MetricCull_Report_${repoName}.md`;
  link.click();
};
